### ISSUE TITLE
ImportError: _py_diff_pd_core.so : undefined symbol: PyCMethod_New

### ISSUE THREAD

**Issue by Duckkkkky** [mit-gfx/diff_pd_public#1]
Hello, thanks a lot for your amazing work. I unexpectedly met with such error when trying to run "python routing_tendon_3d.py":

Traceback (most recent call last):
  File "routing_tendon_3d.py", line 11, in <module>
from py_diff_pd.common.common import ndarray, create_folder, rpy_to_rotation, rpy_to_rotation_gradient
  File "../py_diff_pd/common/common.py", line 52, in <module>
from py_diff_pd.core.py_diff_pd_core import StdRealVector
  File "../py_diff_pd/core/py_diff_pd_core.py", line 13, in <module>
from . import _py_diff_pd_core
ImportError: ../py_diff_pd/core/_py_diff_pd_core.so: undefined symbol: PyCMethod_New`

I have created a conda env following the guidance, (remove nomkl because of packages conflict, and install pytorch 1.7 for cuda 11.0+), using RTX 3080 in Ubuntu 22.04.  The whole compilation process can proceed normally without any error (and I have modified the CMakeLists.txt to find python3.8.3), but when I use "ldd -r" to check the .so file, I found more than one undefined symbols. It seems that something goes wrong during the compilation process, but I have no idea how to fix it. Do you have any ideas?

**Comment by Duckkkkky** [comment]
Okay, I found that when I use sudo to run install.sh the error would occur and cmake would not point to correct python version in my virtual env. Now I solved it.
